BaiLian/urls.py
from django.conf.urls import url

from BaiLian import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^myCart/$',views.myCart,name='myCart'),
    url(r'^shop/(\d+)/$',views.shop,name='shop'),
    url(r'^addcart/$',views.addcart,name='addcart'),
    url('^jiancart/$',views.jaincart,name='jiancart'),
    url('^changestatus/$',views.changestatus,name='changestatus'),
    url('^allchange/$',views.allchange,name='allchange'),
    url('^generateorder/$',views.generateorder,name='generateorder'),
    url('^orderinfo/(\d+)/$',views.orderinfo,name='orderinfo'),
    url('^pay/$',views.pay,name='pay'),        #支付
    url('^notifyurl/$',views.notifyurl,name='notifyurl'),  #支付完成后的通知
    url('^returnurl/$',views.returnurl,name='returnurl')  #支付完成后的通知
]

Project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('BaiLian.urls',namespace='bl'))
]

BaiLian/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=256)
    tel = models.CharField(max_length=50)
    mail = models.CharField(max_length=50)
    #唯一标识令牌
    token = models.CharField(max_length=256,default='')



class Goods(models.Model):
    indeximg = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    price = models.CharField(max_length=50)
    cost = models.CharField(max_length=50)
    init = models.CharField(max_length=10)
    img1 = models.CharField(max_length=255)
    img2 = models.CharField(max_length=255)
    img3 = models.CharField(max_length=255)
    img4 = models.CharField(max_length=255)


class Slideshow(models.Model):
    img = models.CharField(max_length=100)



class Cart(models.Model):
    user = models.ForeignKey(User)
    goods =models.ForeignKey(Goods)
    number = models.IntegerField()
    isselect = models.BooleanField(default=True)

#订单
#一个用户对应多个订单
#在从表这声名关系
class Order(models.Model):
    # 用户
    user = models.ForeignKey(User)
    #订单创建时间
    createtime = models.DateTimeField(auto_now_add=True)
    #状态
    status = models.IntegerField(default=1)
    #订单号
    identifier = models.CharField(max_length=256)


#订单商品
#一个订单对应多个商品
#在从表中声名关系

class OrderGoods(models.Model):
    #订单
    order = models.ForeignKey(Order)
    #商品
    goods = models.ForeignKey(Goods)
    #个数
    number = models.IntegerField(default=1)

templates/login.html
<!DOCTYP< html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>欢迎登录--百联</title>
		<link rel="stylesheet" href="../static/css/reset.css" type="text/css" />
		<link rel="stylesheet" href="../static/css/login.css" type="text/css" />
		<script src="../static/js/jquery-1.12.3.js"></script>
		<script src="../static/js/jquery.cookie.js"></script>
		<script src="../static/js/login.js"></script>
	</head>
	<body>
		<div class="top main">
			<a href="login.html"><img src="../static/images/logo.png" style="width: 159px;" /></a>
			<img src="../static/images/login.png" style="width: 127px;" />
		</div>
		<div class="box">
			<div class="box_top">
				<a href="login.html">会员登录</a>
				<a href="register.html">注册新账号</a>
			</div>
            <form action="/login/" method="post">
                {% csrf_token %}
			<div id="box1">
				<input type="text" placeholder="用户名/手机号/邮箱" name="username"/>
			</div>
			<div id="box2">
				<input type="password" placeholder="密码" name="password"/>
			</div>
			<div id="box3">
				<a href="">忘记密码?</a>
			</div>
			<div id="box4">
				<input type="submit" value="登录" />
			</div>
			<div id="box5">
				<a href="">百联通会员卡首次登录</a>
			</div>
			<div id="box6">
				<p>其他账号联合登录:</p>
			</div>
			<div id="box7">
				<ul>
					<li></li>
					<li></li>
					<li></li>
					<li></li>
					<li></li>
				</ul>
			</div>
            </form>
		</div>
		<div class="bot">
			<div class="main">
				<div>
					<a href="">关于我们</a>
					<a href="">联系我们</a>
					<a href="">加盟合作</a>
					<a href="">诚征英才</a>
					<a href="">友情链接</a>					
				</div>
				<div>
					<p>上海百联全渠道电子商务有限公司 版权所有 | 沪ICP备15028847号</p>
					<p>联系地址：上海市普陀区真光路1258号百联中环广场6楼 | 联系电话：021-52629933 | 咨询热线：400-900-8800</p>
					<p>本企业已通过ISO9001:2000 质量管理体系标准认证 | 认证注册号：04206Q10079ROM | 认可注册号：CNAB042-Q | 增值电信业务经营许可证：沪B2-20100062 97.33</p>
				</div>
			</div>
		</div>
	</body>
</html>

templates/order.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
    <link type="text/css" rel="stylesheet" href="{% static 'css/reset.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <style>
        ul, li {
            list-style: none;
        }

        .img {
            width: 40px;
            height: 30px;
        }

        .num {
            width: 30px;
            text-align: center;
        }

        body {
            position: relative;
            width: 100%;
        }

        .main {
            width: 1190px;
            margin: 0 auto;
        }

        .aposition {
            position: relative;
            margin-top: 20px;
        }

        img {
            cursor: pointer;
        }

        /*头部顶栏样式*/
        .top {
            height: 32px;
            width: 100%;
            border-bottom: solid 1px #e9e9e9;
            border-top: solid 1px #fff;
            background: #f7f7f7;
            box-sizing: border-box;
        }

        .top a {
            cursor: pointer;
        }

        .top a:hover {
            color: red;
        }

        .top .left-top {
            display: inline-block;
        }

        .top .left-top li, .top .right-top li {
            display: inline-block;
            line-height: 30px;
        }

        .top .left-top li a:hover, .inpt-ul li a:hover {
            color: #E6133C;
        }

        .top .right-top {
            float: right;
        }

        #list111 li {
            width: 100%;
            height: 50px;
            background: #fffaf1;
            padding: 10px;
            margin-bottom: 2px;
            border: solid 1px #C01133;
        }

        #list111 li img {
            width: 50px;
            height: 50px;
        }

        .ali {
            float: right;
            margin-right: 30px;
        }

        #acc {
            display: none;
        }

        .ali input {
            width: 80px;
            height: 42px;
            background: #C01133;
            border: none;
            color: #fff;
            font-size: 22px;
        }

        #delSelect {
            float: right;
        }

        .ppp {
            font-size: 24px;
        }

        #da {
            min-height: 400px;
        }
    </style>
    <script src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/order.js' %}"></script>
</head>
<body>
<div class="top" id="top">
    <div class="main">
        <ul class="left-top">
            <li><img src="{% static 'images/top1.jpg' %}"/></li>
            <li>百联集团旗下全渠道电商平台</li>
            <li><a href="">网站导航</a></li>
            <li><a href="">消息</a></li>
        </ul>
        <ul class="right-top">
            <li><a href="{% static 'html/login.html' %}" class="iconfont">&#xe601; 请登录</a>&nbsp;&nbsp;<a
                    href="{% static 'html/register.html' %}">注册</a></li>
            <li><a href="">我的订单</a></li>
            <li><a href="">我的百联</a></li>
            <li><a href="">充值缴费</a></li>
            <li><a href="">客户服务</a></li>
            <li><a href="">掌上百联</a></li>
            <li><a href="">购物车</a></li>
        </ul>
    </div>

</div>
<div class="main" style="margin-top: 20px;">
    <a href="index.html"><img src="{% static 'images/banner.jpg' %}"/></a>
    <h1>订单号:{{ order.identifier }}</h1>
</div>
    <div style="float: right;"><a style="float: left;">登录可永久保存购物车</a></div>
    <br/>
    <hr/>
    <div class="cart">
        <ul id="list111">
            {% for orderGoods in order.ordergoods_set.all %}
                <li>
                <div class="img" style="position: relative;float: left">
                    <img src="{{ orderGoods.goods.img2 }}" alt="" style="position: relative;float: left">
                </div>
                <div class="content" style="position: relative; float: right; margin-right: 20px">
                    <h3 class="name2">
                        {{ orderGoods.goods.name }}
                    </h3>
                    <span class="price2"style="color: red">
                        价格:{{ orderGoods.goods.init }}{{ orderGoods.goods.price }}
                    </span>
                    <span class="number">
                        数量:X{{ orderGoods.number }}
                    </span>
                </div>
                </li>
            {% endfor %}

        </ul>
    </div>
    <p class="ppp">总价：<span id="total">{{ pager }}</span>元</p>

    <div class="ali">
        <input type="button" value="付款" id="pay" identifier="{{ order.identifier }}"/>
    </div>
</div>

<div class="bott">
    <div class="main" id="sx">
        <ul id="xs">
            <li>关于我们</li>
            <li>联系我们</li>
            <li>加盟合作</li>
            <li>诚征英才</li>
            <li>友情链接</li>
        </ul>
        <p>百联集团有限公司旗下 上海百联全渠道电子商务有限公司版权所有 | 客服电话：400-900-8800 | 沪ICP备15028847号</p>
        <p><a href="http://res12.iblimg.com/respc-1/resources/v4.0/img/yaopingzigezheng.png?bl_mmc=blemall_-_0_-_0_-_0">互联网药品信息服务资质证书编号：沪-（非营业性）-2016-0044</a>
        </p>
        <ul id="xs1">
            <li>
                <img src="{% static 'images/ha/gongan.png' %}"/>
                <a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=31010102002366&bl_mmc=blemall_-_0_-_0_-_0">沪公网安备
                    31010102002366号 </a>
            </li>
            <li>
                <img src="{% static 'images/ha/gongs.png' %}"/>
                <a href="http://shwg.dianping.com/?bl_mmc=blemall_-_0_-_0_-_0">网购大家评</a>
            </li>
            <li>
                <img src="{% static 'images//ha/wangjing.png' %}"/>
                <a href="http://218.242.124.22:8081/businessCheck/verifKey.do?showType=extShow&serial=9031000020160729145737000001099658-SAIC_SHOW_310000-20160406145114141192&signData=MEYCIQCUhx+ulQL4t9jJgfgCH1oeTxexuWOVww3Hel3/UlRyLQIhAO2fVtZDl0EkYb0p/3M50cXqe694wDQoJNuUKNdQNOWf&bl_mmc=blemall_-_0_-_0_-_0">上海工商</a>
            </li>
            <li>
                <img src="{% static 'images/ha/zhizhao.png' %}"/>
                <a href="http://promotion.bl.com/nc/PC_HDGL20170407000001552_1592.html?bl_mmc=blemall_-_0_-_0_-_0">经营执照</a>
            </li>
        </ul>
    </div>
</div>
</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>欢迎注册--百联</title>
		<link href="../static/css/reset.css" type="text/css" rel="stylesheet" />
		<link href="../static/css/regist.css" type="text/css" rel="stylesheet" />
		<script src="../static/js/jquery-1.12.3.js"></script>
		<script src="../static/js/jquery.cookie.js"></script>
		<script src="../static/js/gVerify.js"></script>
		<script src="../static/js/register.js"></script>
	</head>
	<body>
		<div class="top main">
			<a href="http://www.bl.com/?bl_mmc=blemall_-_0_-_0_-_0"><img src="../static/images/logo.png" style="width: 159px;" /></a>
			<img src="../static/images/yonghu.png" style="width: 127px;" />
		</div>
		<div class="box main">
			<div class="box_p">
				<a style="color: red;">您好，感谢您加入i百联</a>
				<div class="right-a">
					<a>如有账号，请 </a>
					<a href="login.html" style="color:blue !important">登录</a>
				</div>
			</div>
			<div class="form-inpt">
                <form action="/register/" method="post">
                    {% csrf_token %}
					<div class="inpt1">
						<div class="inpt-i">
							<i>*</i>用户名:
						</div>
						<div class="input-1">
							<input class="inpt-show" id="inpt-show1" type="text" placeholder="6-20位字符，支持字母或字母与数字组合" name="username"/>
						</div>
						<span>
							<img src="../static/images/yn.png" />
							<a>请输入用户名</a>
						</span>
					</div>
					<div class="inpt1">
						<div class="inpt-i">
							<i>*</i>登录密码:
						</div>
						<div class="input-1">
							<input class="inpt-show" id="inpt-show2" type="password" placeholder="8-20位字符，至少使用两种字符组合" name="password" />
						</div>
						<span>
							<img src="../static/images/yn.png" />
							<a>密码强度</a>
							<ul>
								<li>弱</li>
								<li>中</li>
								<li>强</li>
							</ul>
						</span>
					</div>	
					<div class="inpt1">
						<div class="inpt-i">
							<i>*</i>确认密码:
						</div>
						<div class="input-1">
							<input class="inpt-show" id="inpt-show3" type="password" placeholder="请再次输入密码" />
						</div>
						<span>
							<img src="../static/images/yn.png" />
							<a></a>
						</span>
					</div>
					<div class="inpt1">
						<div class="inpt-i">
							<i>*</i>手机号:
						</div>
						<div class="input-1">
							<input class="inpt-show" id="inpt-show4" type="text" placeholder="请输入11位手机号码" maxlength="11" name="tel" />
						</div>
						<span>
							<img src="../static/images/yn.png" />
							<a></a>
						</span>
					</div>
					<div class="inpt1">
						<div class="inpt-i">
							<i>*</i>验证码:
						</div>
						<div class="input-1" id="inpt5">
							<input id="inpt-show5" class="inpt-show2" type="text" placeholder="请输入验证码" />
							<div id="v_container"  style="width: 90px;height: 34px;" class="inpt-show3"></div>				
						</div>
						<span>
							<img src="../static/images/yn.png" />
							<a></a>
						</span>
					</div>
					<div class="inpt1">
						<div class="inpt-i">
							<i>*</i>短信验证码:
						</div>
						<div class="input-1" id="inpt5">
							<input id="inpt-show6" class="inpt-show2" type="text" placeholder="请输入短信验证码" name="" />
							<input type="submit" value="点击获取" class="inpt-show3" />
						</div>
						<span>
							<img src="../static/images/yn.png" />
							<a></a>
						</span>
					</div>	
					<div class="inpt1">
						<div class="inpt-i">
							<i>*</i>电子邮箱:
						</div>
						<div class="input-1">
							<input class="inpt-show" id="inpt-show7" type="email" placeholder="请输入有效邮箱" required name="E-mail"/>
						</div>
						<span>
							<img src="../static/images/yn.png" />
							<a></a>
						</span>
					</div>
                    <div class="inpt-i"></div>
						<input type="checkbox" id="check" />
						<a>   我已阅读并同意   </a>
						<a style="color: blue;" href="http://help.bl.com/articleDetailed.html?articleId=382&&categoryType=help&bl_mmc=blemall_-_0_-_0_-_0">《百联通会员注册协议》</a>
						<br /><br />
{#						<input class="input-1" id="inpt-show8" type="submit" value="立即注册 完成绑定" />#}
                        <input type="submit" style="background: red; width:300px; height: 30px; border-radius: 10px" value="登陆">
                </form>
			</div>
		</div>
		<div class="bot">
			<div class="main">
				<div>
					<a href="">关于我们</a>
					<a href="">联系我们</a>
					<a href="">加盟合作</a>
					<a href="">诚征英才</a>
					<a href="">友情链接</a>					
				</div>
				<div>
					<p>上海百联全渠道电子商务有限公司 版权所有 | 沪ICP备15028847号</p>
					<p>联系地址：上海市普陀区真光路1258号百联中环广场6楼 | 联系电话：021-52629933 | 咨询热线：400-900-8800</p>
					<p>本企业已通过ISO9001:2000 质量管理体系标准认证 | 认证注册号：04206Q10079ROM | 认可注册号：CNAB042-Q | 增值电信业务经营许可证：沪B2-20100062 97.33</p>
				</div>
			</div>
		</div>
	</body>
</html>

templates/shop.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>商品详情</title>
		<link rel="stylesheet" href="{% static 'css/shop.css' %}" type="text/css" />
		<link rel="stylesheet" href="{% static 'css/reset.css' %}" type="text/css" />
		<script src="{% static 'js/jquery-1.12.3.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}" ></script>
		<script src="{% static 'js/shop.js' %}"></script>
	</head>
	<body>
		<!--商品页重做- 多div包裹写法-->
		 <div id="top">
        	<div class="main">
        		<ul id="ul1">
        			<li id="top1"><a>百联集团666</a></li>
        			<li id="top2"><a href="">网站导航</a></li>
        			<li id="top3"><a href="">消息</a></li>
        		</ul>
        		<ul id="ul2">
        			<li><a href="{% static 'html/login.html' %}">登录</a><a href="{% static 'html/register.html' %}">注册</a></li>
        			<li><a href="">我的订单</a></li>
        			<li><a href="">我的百联</a></li>
        			<li><a href="">充值缴费</a></li>
        			<li><a href="">客户服务</a></li>
        			<li><a href="">掌上百联</a></li>
        			<li><a href="">购物车</a></li>
        		</ul>
        	</div>
        </div>

        <!--banner logo 部分-->
        <div style="height: 78px;padding-bottom: 18px;">
        	<div class="main">
        		<div id="logo">
	        		<div>
	        			<a href="index.html"><img src="{% static 'images/banner.jpg' %}" /></a>
	        		</div>
	        		<div>
	        			<img src="{% static 'images/342870273.jpg' %}" />
	        		</div>
        		</div>
        		<div id="so">
	         		<div id="Inpt">
	        			<input type="text" placeholder="10Q币只卖9.9！马化腾：‘亏死了’" /><input type="submit" value="" class="" />
	        		</div>
	        		<div id="first-a">
	        			<a href="">iPhone</a>
	        			<a href="">耐克</a>
	        			<a href="">大王</a>
	        			<a href="">欧舒丹</a>
	        			<a href="">手表</a>
	        			<a href="">良品铺子</a>
	        			<a href="">卫生纸</a>
	        			<a href="">沐浴露</a>
	        			<a href="">大米</a>
	        			<a href="" style="border:none !important">大王天使</a>
	        		</div>
        		</div>
        	</div>
        </div>

        <!--这里是黑色的列表-->
        <div id="black">
        	<div class="main">
        		<div id="txt">
        			<a>商品详情      </a>
        		</div>
        		<ul>
        			<li><a href="">首页</a></li>
        			<li><a href="">生活日用</a></li>
        			<li><a href="">24H百货</a></li>
        			<li><a href="">全球购</a></li>
        			<li><a href="">精品闪购</a></li>
        			<li><a href="">电器城</a></li>
        			<li><a href="">奥莱代购</a></li>
        			<li><a href="">礼品卡</a></li>
        		</ul>
        	</div>
        </div>

        <div style="height: 650px;">
        	<div class="main">
        		<div>
        			<div>
        				<p></p>
        				<!--这里是json 来的产品路径归属-->
        			</div>
        			<div>
        				<img src="" />
        				<!--这里是json 来的产品品牌信息图-->
        			</div>
        		</div>
        		<!--楼上应该有个下边框-->
        	</div>
        	<div class="main">
        		<!--这里是左边的切换图-->
        		<div id="left">
        			<div id="smallImg">
        				<img src="{{ good.img1 }}"  width="448" height="448"  />
        				<div id="smallArea"></div>
        			</div>
        			<div id="bigArea">
        				<img id="bigImg" src="" width="600" height="600" />
        			</div>
        			<div id="four">
        				<!--这里是4个商品小图-->
        				<div id="img1"><img src="{{ good.img1 }}" /></div>
        				<div id="img2"><img src="{{ good.img2 }}" /></div>
        				<div id="img3"><img src="{{ good.img3 }}" /></div>
        				<div id="img4"><img src="{{ good.img4 }}" /></div>
        			</div>
        		</div>
        		<!--这里是右边的商品详情-->
        		<div style="width: 710px;float: left;margin-left: 10px;">
        			<div class="namebox">
        				<!--获取商品name-->
        				<p>{{ good.name }}</p>
        			</div>
        			<div id="bebox">
        				<div id="redbox">
        					<a>超值团</a>
        					<a>距离活动结束还有</a>
        					<a></a>
        					<a>更多活动  > </a>
        				</div>
        				<div id="prbox">
        					<div id="prbox1">
        						<a>活动价</a>
        					</div>
        					<div class="pricebox">
        						<p>
        							{{ good.init }}{{ good.price }}
        						</p>
        					</div>
        					<div id="rate">
        						<a>8.3折</a>
        					</div>
        					<div id="costbox">
        						<a>参考价：</a>
        						<a>
        							{{ good.init }}{{ good.cost }}
        						</a>
        					</div>
        				</div>
        			</div>
        			<div class="waibao">

        					<a class="left">配送</a>


        					<a>
        						99元免基础运费（5kg内）
        					</a>

        			</div>
        			<div>
        				<div class="left">
        					<a>服务</a>
        				</div>
        				<div>
	        				<div>
	        					<a>由</a>
	        					<a>
	        						<!--发货方-->
	        					</a>
	        					<a>提供发货和售后服务，预计1-2天送达</a>
	        				</div>
	        				<div id="olli">
	        					<ol>
	        						<li>不支持到店自提</li>
	        						<li>不支持7天无理由退货</li>
	        						<li>不支持货到付款</li>
	        					</ol>
	        				</div>
        				</div>
        			</div>
        			<div style="width: 710px;height: 28px;padding: 15px 0;">
        				<div class="left">
        					<a>购买数量</a>
        				</div>
        				<div style="float: left;">
	        				<button style="float: left;width: 20px;height: 20px;" class="jiancaozuo" goodsid = {{ good.id }}>-</button>
                            <input id="ini" type="text" style="width: 18px;height: 16px;float: left;" value="{{ cart.number }}"/>
	        				<button style="float: left;width: 20px;height: 20px;" class="jiacaozuo" goodsid = {{ good.id }}>+</button>
        				</div>

        				<a style="margin-left: 20px;float: left;">限购20件</a>

        			</div>
        			<div style="width: 710px;height: 48px;">
						<div class="left">
							<!--空div-->
						</div>
						<div id="box-two">
							<div>立刻购买</div>
                            <div><a href="{% url 'bl:myCart' %}" target="_self">加入购物车</a></div>
							<div>
								<a>收藏</a>
							</div>
						</div>
        			</div>
        			<div style="width: 710px;height: 48px;">
        				<div>
        					<!--空-->
        				</div>
        				<div>
        					<a>100%好评</a>
        					<a>
        						<!--评价-->
        					</a>
        					<a href="">评价返积分</a>
        				</div>
        			</div>
        		</div>
        	</div>
        </div>

        <div id="boxtj">
        	<div class="main">
        		<div>
        			<div id="tuijian">
        				<p>购买此商品的顾客也会购买：</p>
        			</div>
        			<div>
        				<ul id="tj">
        					<li>
        						<a href="shop.html?id=001"><img src="{% static 'images/ha/img1.jpg' %}" /></a>
        						<div class="namebox">
        							<p>
        								<!--name-->
        							</p>
        						</div>

        						<div class="pricebox">
        							<p>
        								<!--价格-->
        							</p>
        						</div>

        					</li>
        					<li>
        						<a href="shop.html?id=002"><img src="{% static 'images/ha/img2.jpg' %}" /></a>
        						<div class="namebox">
        							<p>
        								<!--name-->
        							</p>
        						</div>

        						<div class="pricebox">
        							<p>
        								<!--价格-->
        							</p>
        						</div>

        					</li>
        					<li>
        						<a href="shop.html?id=003"><img src="{% static 'images/ha/img3.jpg' %}" /></a>
        						<div class="namebox">
        							<p>
        								<!--name-->
        							</p>
        						</div>

        						<div class="pricebox">
        							<p>
        								<!--价格-->
        							</p>
        						</div>
        					</li>
        					<li>
        						<a href="shop.html?id=004"><img src="{% static 'images/ha/img4.jpg' %}" /></a>
        						<div class="namebox">
        							<p>
        								<!--name-->
        							</p>
        						</div>

        						<div class="pricebox">
        							<p>
        								<!--价格-->
        							</p>
        						</div>


        					</li>
        					<li>
        						<a href="shop.html?id=005"><img src="{% static 'images/ha/img5.jpg' %}" /></a>
        						<div class="namebox">
        							<p>
        								<!--name-->
        							</p>
        						</div>

        						<div class="pricebox">
        							<p>
        								<!--价格-->
        							</p>
        						</div>
        					</li>
        				</ul>
        			</div>
        		</div>
        	</div>
        </div>

        <!--底部-->

         <div id="bt">
        	<div class="main">
        		<dl>
        			<dt>新手入门</dt>
	        			<dd><a href="">购物流程</a></dd>
	        			<dd><a href="">会员介绍</a></dd>
	        			<dd><a href="">常见问题</a></dd>
	        			<dd><a href="">发票说明</a></dd>
	        			<dd><a href="">联系客服</a></dd>
        		</dl>
        		<dl>
        			<dt>配送服务</dt>
	        			<dd><a href="">配送范围及运费</a></dd>
	        			<dd><a href="">配送进度查询</a></dd>
	        			<dd><a href="">自提服务</a></dd>
	        			<dd><a href="">商品验货与签收</a></dd>
        		</dl>
        		<dl>
        			<dt>支付方式</dt>
        				<dd><a href="">货到付款</a></dd>
        				<dd><a href="">在线支付</a></dd>
        		</dl>
        		<dl>
        			<dt>售后服务</dt>
        				<dd><a href="">退换货政策</a></dd>
        				<dd><a href="">退换货流程</a></dd>
        				<dd><a href="">退款说明</a></dd>
        		</dl>
       			<dl id="dl5">
       				<dt>商家支持</dt>
       					<dd><a href="">商家入驻</a></dd>
       					<dd><a href="">商家规则</a></dd>
       					<dd><a href="">商家常见问题</a></dd>
       			</dl>
        	</div>
        </div>
        <!--最底部-->
        	<div class="main">
        		<div style="margin: 10px auto;width: 255px;">
        			<a href="">关于我们</a>
        			<a href="">联系我们</a>
        			<a href="">加盟合作</a>
        			<a href="">诚征英才</a>
        			<a href="">友情链接</a>
        		</div>
        		<div style="margin:10px auto;width: 625px;">
        			百联集团有限公司旗下 上海百联全渠道电子商务有限公司版权所有 | 客服电话：400-900-8800 | 沪ICP备15028847号
        		</div>
        		<div style="width: 348px;margin: 10px auto;">
        			<a href="">互联网药品信息服务资质证书编号：沪-（非营业性）-2016-0044</a>
        		</div>
        		<div style="margin: 10px auto;width: 342px;">
        			<a href="">沪公网安备 31010102002366号</a>
        			<a href="">网购大家评</a>
        			<a href="">上海工商</a>
        			<a href="">经营执照</a>
        		</div>
        	</div>

	</body>
</html>